package Constants;

public enum CountryData {

    AFGHANISTAN("Q1845", "Afghanistan"),
    ALBANIA("Q233", "Albania"),
    ALGERIA("Q262", "Algeria"),
    ANDORRA("Q258", "Andorra"),
    ANGOLA("Q1023", "Angola"),
    ANTIGUA_AND_BARBUDA("Q3128", "Antigua and Barbuda"),
    ARGENTINA("Q414", "Argentina"),
    ARMENIA("Q399", "Armenia"),
    AUSTRALIA("Q408", "Australia"),
    AUSTRIA("Q40", "Austria"),
    AZERBAIJAN("Q398", "Azerbaijan"),
    BAHAMAS("Q3127", "Bahamas"),
    BAHRAIN("Q1007", "Bahrain"),
    BANGLADESH("Q902", "Bangladesh"),
    BARBADOS("Q756", "Barbados"),
    BELARUS("Q1860", "Belarus"),
    BELGIUM("Q31", "Belgium"),
    BELIZE("Q1065", "Belize"),
    BENIN("Q1027", "Benin"),
    BHUTAN("Q2340", "Bhutan"),
    BOLIVIA("Q750", "Bolivia"),
    BOSNIA_AND_HERZEGOVINA("Q1531", "Bosnia and Herzegovina"),
    BOTSWANA("Q1005", "Botswana"),
    BRAZIL("Q155", "Brazil"),
    BRUNEI("Q1089", "Brunei Darussalam"),
    BULGARIA("Q219", "Bulgaria"),
    BURKINA_FASO("Q1001", "Burkina Faso"),
    BURUNDI("Q1024", "Burundi"),
    CAMBODIA("Q1080", "Cambodia"),
    CAMEROON("Q1007", "Cameroon"),
    CANADA("Q16", "Canada"),
    CAPE_VERDE("Q1032", "Cape Verde"),
    CAR("Q1030", "Central African Republic"),
    CHAD("Q1035", "Chad"),
    CHILE("Q298", "Chile"),
    CHINA("Q148", "China"),
    COLOMBIA("Q739", "Colombia"),
    CONGO_REPUBLIC("Q1034", "Congo, Republic of the..."),
    COSTA_RICA("Q811", "Costa Rica"),
    COTE_DIVOIRE("Q1026", "Côte d'Ivoire"),
    CROATIA("Q224", "Croatia"),
    CUBA("Q279", "Cuba"),
    CYPRUS("Q229", "Cyprus"),
    CZECH_REPUBLIC("Q213", "Czech Republic"),
    DEMOCRATIC_PEOPLE("Q402", "Democratic People's Republic of Korea"),
    DENMARK("Q35", "Denmark"),
    DJIBOUTI("Q1045", "Djibouti"),
    DOMINICA("Q289", "Dominica"),
    DOMINICAN_REPUBLIC("Q739", "Dominican Republic"),
    DR_CONGO("Q1065", "Democratic Republic of the Congo"),
    ECUADOR("Q739", "Ecuador"),
    EGYPT("Q79", "Egypt"),
    EL_SALVADOR("Q744", "El Salvador"),
    EQUATORIAL_GUINEA("Q1050", "Equatorial Guinea"),
    ESTONIA("Q1917", "Estonia"),
    ETHIOPIA("Q115", "Ethiopia"),
    FIJI("Q672", "Fiji"),
    FINLAND("Q33", "Finland"),
    FRANCE("Q6256", "France"),
    GABON("Q1053", "Gabon"),
    GEORGIA("Q2331", "Georgia"),
    GERMANY("Q183", "Germany"),
    GHANA("Q116", "Ghana"),
    GREECE("Q41", "Greece"),
    GUATEMALA("Q774", "Guatemala"),
    GUINEA("Q1019", "Guinea"),
    GUINEA_BISSAU("Q1006", "Guinea-Bissau"),
    GUYANA("Q277", "Guyana"),
    HAITI("Q1027", "Haiti"),
    HONDURAS("Q771", "Honduras"),
    HONG_KONG("Q8657", "Hong Kong (S.A.R.)"),
    HUNGARY("Q28", "Hungary"),
    ICELAND("Q1890", "Iceland"),
    INDIA("Q668", "India"),
    INDONESIA("Q795", "Indonesia"),
    IRAN("Q794", "Iran, Islamic Republic of..."),
    IRAQ("Q794", "Iraq"),
    IRELAND("Q1860", "Ireland"),
    ISLE_OF_MAN("Q1860", "Isle of Man"),
    ISRAEL("Q801", "Israel"),
    ITALY("Q38", "Italy"),
    JAMAICA("Q774", "Jamaica"),
    JAPAN("Q17", "Japan"),
    JORDAN("Q811", "Jordan"),
    KAZAKHSTAN("Q232", "Kazakhstan"),
    KENYA("Q114", "Kenya"),
    KOSOVO("Q1531", "Kosovo"),
    KUWAIT("Q817", "Kuwait"),
    KYRGYZSTAN("Q243", "Kyrgyzstan"),
    LAOS("Q928", "Lao People's Democratic Republic"),
    LATVIA("Q1917", "Latvia"),
    LEBANON("Q794", "Lebanon"),
    LESOTHO("Q1062", "Lesotho"),
    LIBERIA("Q1034", "Liberia"),
    LIBYAN_ARAB_JAMAHIRIYA("Q1126", "Libyan Arab Jamahiriya"),
    LIECHTENSTEIN("Q1046", "Liechtenstein"),
    LITHUANIA("Q2111", "Lithuania"),
    LUXEMBOURG("Q1860", "Luxembourg"),
    MADAGASCAR("Q1004", "Madagascar"),
    MALAWI("Q951", "Malawi"),
    MALAYSIA("Q833", "Malaysia"),
    MALDIVES("Q847", "Maldives"),
    MALI("Q1023", "Mali"),
    MALTA("Q2330", "Malta"),
    MAURITANIA("Q1062", "Mauritania"),
    MAURITIUS("Q1111", "Mauritius"),
    MEXICO("Q799", "Mexico"),
    MICRONESIA("Q1026", "Micronesia, Federated States of..."),
    MOLDOVA("Q250", "Republic of Moldova"),
    MONACO("Q1025", "Monaco"),
    MONGOLIA("Q389", "Mongolia"),
    MONTENEGRO("Q2184", "Montenegro"),
    MOROCCO("Q1031", "Morocco"),
    MOZAMBIQUE("Q1021", "Mozambique"),
    MYANMAR("Q836", "Myanmar"),
    NAMIBIA("Q1035", "Namibia"),
    NAURU("Q1030", "NA"),
    NEPAL("Q156", "Nepal"),
    NETHERLANDS("Q55", "Netherlands"),
    NEW_ZEALAND("Q664", "New Zealand"),
    NICARAGUA("Q717", "Nicaragua"),
    NIGER("Q1028", "Niger"),
    NIGERIA("Q1037", "Nigeria"),
    NOMADIC("Q159", "Nomadic"),
    NORTH_KOREA("Q402", "North Korea"),
    NORTH_MACEDONIA("Q213", "Republic of North Macedonia"),
    NORWAY("Q20", "Norway"),
    OMAN("Q784", "Oman"),
    PAKISTAN("Q1860", "Pakistan"),
    PALESTINE("Q3143", "Palestine"),
    PANAMA("Q271", "Panama"),
    PAPUA_NEW_GUINEA("Q335", "Papua New Guinea"),
    PARAGUAY("Q1025", "Paraguay"),
    PERU("Q419", "Peru"),
    PHILIPPINES("Q928", "Philippines"),
    POLAND("Q36", "Poland"),
    PORTUGAL("Q45", "Portugal"),
    QATAR("Q847", "Qatar"),
    ROMANIA("Q218", "Romania"),
    RUSSIA("Q159", "Russian Federation"),
    RWANDA("Q1036", "Rwanda"),
    SAINT_KITTS_AND_NEVIS("Q1065", "Saint Kitts and Nevis"),
    SAMOA("Q1043", "Samoa"),
    SAN_MARINO("Q2364", "San Marino"),
    SAUDI_ARABIA("Q848", "Saudi Arabia"),
    SENEGAL("Q1031", "Senegal"),
    SERBIA("Q403", "Serbia"),
    SIERRA_LEONE("Q1030", "Sierra Leone"),
    SINGAPORE("Q334", "Singapore"),
    SLOVAKIA("Q214", "Slovakia"),
    SLOVENIA("Q2132", "Slovenia"),
    SOLOMON_ISLANDS("Q1057", "Solomon Islands"),
    SOMALIA("Q1030", "Somalia"),
    SOUTH_AFRICA("Q258", "South Africa"),
    SOUTH_KOREA("Q884", "Republic of Korea"),
    SPAIN("Q1860", "Spain"),
    SRI_LANKA("Q864", "Sri Lanka"),
    SUDAN("Q786", "Sudan"),
    SURINAME("Q1066", "Suriname"),
    SWAZILAND("Q858", "Swaziland"),
    SWEDEN("Q34", "Sweden"),
    SWITZERLAND("Q39", "Switzerland"),
    SYRIA("Q858", "Syrian Arab Republic"),
    TAIWAN("Q8657", "Taiwan"),
    TAJIKISTAN("Q998", "Tajikistan"),
    TANZANIA("Q945", "United Republic of Tanzania"),
    THAILAND("Q869", "Thailand"),
    TOGO("Q1020", "Togo"),
    TRINIDAD_AND_TOBAGO("Q758", "Trinidad and Tobago"),
    TUNISIA("Q1877", "Tunisia"),
    TURKEY("Q43", "Turkey"),
    TURKMENISTAN("Q2681", "Turkmenistan"),
    UAE("Q842", "United Arab Emirates"),
    UGANDA("Q1036", "Uganda"),
    UKRAINE("Q212", "Ukraine"),
    UNITED_KINGDOM("Q1860", "United Kingdom of Great Britain and Northern Ireland"),
    URUGUAY("Q774", "Uruguay"),
    USA("Q30", "United States of America"),
    UZBEKISTAN("Q868", "Uzbekistan"),
    VENEZUELA("Q739", "Venezuela, Bolivarian Republic of..."),
    VIETNAM("Q881", "Viet Nam"),
    YEMEN("Q417", "Yemen"),
    ZAMBIA("Q1042", "Zambia"),
    ZIMBABWE("Q1043", "Zimbabwe");

    private final String wikidataCode;
    private final String countryName;

    CountryData(String wikidataCode, String countryName) {
        this.wikidataCode = wikidataCode;
        this.countryName = countryName;
    }

    public String getWikidataCode() {
        return wikidataCode;
    }

    public String getCountryName() {
        return countryName;
    }

    public static CountryData fromCountryName(String countryName) {
        for (CountryData countryCode : values()) {
            if (countryCode.getCountryName() != null && countryCode.getCountryName().equalsIgnoreCase(countryName)) {
                return countryCode;
            }
        }
        throw new IllegalArgumentException("No enum constant for country: " + countryName);
    }
}
